# Generated by Django 6.0.4 on 2026-04-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoIOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=50)),
                ('fecha_instalacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Microacueducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivoiot')),
            ],
        ),
        migrations.CreateModel(
            name='LecturaNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_litros', models.FloatField()),
                ('nivel_actual', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
                ('microacueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.microacueducto')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tanque'),
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=30)),
                ('microacueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.microacueducto')),
            ],
        ),
        migrations.CreateModel(
            name='Valvula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivoiot')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vivienda')),
            ],
        ),
    ]
