# Generated by Django 6.0.4 on 2026-04-28 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoIOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=50)),
                ('fecha_instalacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Microacueducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url_backend', models.CharField(max_length=100)),
                ('url_frontend', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('recurso_padre', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recurso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=30)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivoiot')),
            ],
        ),
        migrations.CreateModel(
            name='LecturaNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_litros', models.FloatField()),
                ('nivel_actual', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
                ('microacueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.microacueducto')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tanque'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=30)),
                ('microacueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.microacueducto')),
            ],
        ),
        migrations.CreateModel(
            name='Valvula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivoiot')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vivienda')),
            ],
        ),
    ]
